### ISSUE TITLE
This is not a complete project

### ISSUE THREAD

**Issue by LuYuxiang-student** [facebookresearch/HighResCanopyHeight#3]
The code for this project contains a lot of redundancies and is missing numerous files, making it impossible to run directly.

**Comment by coupriec** [comment]
Hi [LuYuxiang](https://github.com/LuYuxiang-student), thanks for reaching out. I checked again, there are no missing files from the repo. I am adding the instructions below to prepare the data to the readme, maybe it will help future users to run the code more directly.  

To prepare the data, in the cloned repository, run these commands: 
aws s3 --no-sign-request cp --recursive s3://dataforgood-fb-data/forests/v1/models/ . 
unzip data.zip

Also don't forget to activate the hrch environment to run inference.py  

Hoping this helps.

**Comment by JohnMBrandt** [comment]
I also was able to get the script to run pretty quickly with the following `mamba` yaml:

```
name: pytorch-mac
channels:
  - apple
  - conda-forge
  - pytorch
dependencies:
  - python=3.10 ## specify desired version
  - pip
  - pytorch==2.0.1
  - rasterio
  - numpy
  - bottleneck
  - hickle
  - torchvision==0.15.2

  ## uncomment for use with Jupyter
  - ipykernel
  - notebook
  - jupyter
  - 
  -

  ## PyPI packages
  - pip:
    - pytorch-lightning==1.7
    - pandas
    - matplotlib
    - torchmetrics==0.11.4 
````

I was able to run inference on the NEON test data quite quickly with `aws s3 --no-sign-request cp --recursive s3://dataforgood-fb-data/forests/v1/models/ .
unzip data.zip` and `python3 inference.py --display True`.

I'm also able to run inference on new images, simply by adjusting the path to the folder, and making a .csv file that is similar to the structure in `neon_test_data.csv`
