### ISSUE TITLE
Do you intend to make the results available as ee.ImageCollection in Google Earth Engine

### ISSUE THREAD

**Issue by bsledz** [facebookresearch/HighResCanopyHeight#5]
Hello, Thank you for your work, it looks interesting

You are currently sharing the view:
https://meta-forest-monitoring-okw37.projects.earthengine.app/view/canopyheight

which allows viewing the results but does not allow further postprocessing of the results. 
Do you intend to make the results available as ee.ImageCollection in Google Earth Engine?

**Comment by coupriec** [comment]
Hi, thanks for your interest, it should be available, see https://gee-community-catalog.org/projects/meta_trees/
